class TranslateController
  def self.translate(controller)
    case controller
      when 'books'
          'Livros'
      when 'students'
          'Alunos'
      when 'calendars'
          'Períodos'
      when 'notes'
          'Mensagens'
      when 'profiles'
          'Perfis'
      when 'classrooms'
          'Turmas'
      when 'teachers'
          'Professores'
      when 'companies'
          'Escolas'
      when 'courses'
          'Cursos'
      when 'events'
          'Eventos'
      when 'exams'
          'Avaliações'
      when 'faults'
          'Faltas'
      when 'groups'
          'Agrupar Alunos'
      when 'rents'
          'Empréstimos'
      when 'users'
          'Usuários'
      when 'calendar_days'
          'Dias(calendários)'
      when 'questions'
          'Perguntas'
      when 'answers'
          'Respostas'
      when 'questionnaires'
          'Questionários'
      when 'lessons'
        'Aulas'
      when 'birthdays_months'
        'Aniversariantes'
    end
  end

  def self.action(action)
    case action
      when 'create'
        'Criar'
      when 'read'
        'Ler'
      when 'update'
        'Atualizar'
      when 'destroy'
        'Apagar'
      when 'schedules'
        'Quadro horários'
      when 'my_data'
        'Minhas informações'
      when 'my_exams'
        'Minhas avaliações'
      when 'events'
        'Eventos'
      when 'finalize'
        'Finalizar'
      when 'bulletin'
        'Boletins'
      when 'generate_lessons'
        'Gerar aulas'
      when 'daily'
        'Diário'
      when 'for_month_print_daily'
        'escolha do mês'
      when 'generate'
        'Gerar questionário'
      when 'down_average'
        'Alunos abaixo da média'
    end
  end
end