roles:
  - books
  - calendar_days
  - calendars
  - classrooms
  - courses
  - events
  - exams
  - faults
  - groups
  - notes
  - rents
  - students
  - teachers
  - profiles
  - companies
  - questions
  - answers
  - questionnaires
  - lessons
  - birthdays_months
  - plans
  - questionnaire_questions
  - enrollments
  - managers
  - control_points
actions:
  - create
  - read
  - update
  - destroy
actions_more_students:
  - my_data
  - my_exams
  - bulletin
  - down_average
  - declaration_of_studying
  - frequency
actions_more_classrooms:
  - schedules
  - generate_lessons
  - daily
  - for_month_print_daily
  - schedules_for_week_day
  - throw_faults
  - report_schedules
  - throw_exams
  - envelopes_for_exams
  - print
actions_more_calendars:
  - events
  - finalize
  - results
  - classrooms
  - re_enrollments
  - report_re_enrollments
actions_more_groups:
  - second_change_exam
  - re_enrollment
  - have_book
actions_more_events:
  - finalize
actions_more_birthdays_months:
  - print
actions_more_rents:
  - returned
actions_more_faults:
  - create_with_click
actions_more_managers:
  - change_companies
  - create_calendar
  - change_calendars
actions_more_enrollments:
  - list_classrooms_to_re_enrollments
  - create_re
actions_more_plans:
  - report
actions_more_teachers:
  - report_teacher
actions_more_courses:
  - buy_books
actions_more_calendar_days:
  - find
actions_more_control_points:
  - info
actions_more_companies:
- print_informations
- students_for_neighborhood
- lists_present