require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CalendarDaysController do

  # This should return the minimal set of attributes required to create a valid
  # CalendarDay. As you add validations to CalendarDay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "day" => "2014-03-31" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CalendarDaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all calendar_days as @calendar_days" do
      calendar_day = CalendarDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:calendar_days).should eq([calendar_day])
    end
  end

  describe "GET show" do
    it "assigns the requested calendar_day as @calendar_day" do
      calendar_day = CalendarDay.create! valid_attributes
      get :show, {:id => calendar_day.to_param}, valid_session
      assigns(:calendar_day).should eq(calendar_day)
    end
  end

  describe "GET new" do
    it "assigns a new calendar_day as @calendar_day" do
      get :new, {}, valid_session
      assigns(:calendar_day).should be_a_new(CalendarDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested calendar_day as @calendar_day" do
      calendar_day = CalendarDay.create! valid_attributes
      get :edit, {:id => calendar_day.to_param}, valid_session
      assigns(:calendar_day).should eq(calendar_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CalendarDay" do
        expect {
          post :create, {:calendar_day => valid_attributes}, valid_session
        }.to change(CalendarDay, :count).by(1)
      end

      it "assigns a newly created calendar_day as @calendar_day" do
        post :create, {:calendar_day => valid_attributes}, valid_session
        assigns(:calendar_day).should be_a(CalendarDay)
        assigns(:calendar_day).should be_persisted
      end

      it "redirects to the created calendar_day" do
        post :create, {:calendar_day => valid_attributes}, valid_session
        response.should redirect_to(CalendarDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved calendar_day as @calendar_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        CalendarDay.any_instance.stub(:save).and_return(false)
        post :create, {:calendar_day => { "day" => "invalid value" }}, valid_session
        assigns(:calendar_day).should be_a_new(CalendarDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CalendarDay.any_instance.stub(:save).and_return(false)
        post :create, {:calendar_day => { "day" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested calendar_day" do
        calendar_day = CalendarDay.create! valid_attributes
        # Assuming there are no other calendar_days in the database, this
        # specifies that the CalendarDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CalendarDay.any_instance.should_receive(:update).with({ "day" => "2014-03-31" })
        put :update, {:id => calendar_day.to_param, :calendar_day => { "day" => "2014-03-31" }}, valid_session
      end

      it "assigns the requested calendar_day as @calendar_day" do
        calendar_day = CalendarDay.create! valid_attributes
        put :update, {:id => calendar_day.to_param, :calendar_day => valid_attributes}, valid_session
        assigns(:calendar_day).should eq(calendar_day)
      end

      it "redirects to the calendar_day" do
        calendar_day = CalendarDay.create! valid_attributes
        put :update, {:id => calendar_day.to_param, :calendar_day => valid_attributes}, valid_session
        response.should redirect_to(calendar_day)
      end
    end

    describe "with invalid params" do
      it "assigns the calendar_day as @calendar_day" do
        calendar_day = CalendarDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CalendarDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => calendar_day.to_param, :calendar_day => { "day" => "invalid value" }}, valid_session
        assigns(:calendar_day).should eq(calendar_day)
      end

      it "re-renders the 'edit' template" do
        calendar_day = CalendarDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CalendarDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => calendar_day.to_param, :calendar_day => { "day" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested calendar_day" do
      calendar_day = CalendarDay.create! valid_attributes
      expect {
        delete :destroy, {:id => calendar_day.to_param}, valid_session
      }.to change(CalendarDay, :count).by(-1)
    end

    it "redirects to the calendar_days list" do
      calendar_day = CalendarDay.create! valid_attributes
      delete :destroy, {:id => calendar_day.to_param}, valid_session
      response.should redirect_to(calendar_days_url)
    end
  end

end
